name: Build Image
on:
  release:
    types: [published]
jobs:
  build:
      runs-on: ubuntu-latest
      name: Build image job
      steps:
          - name: Checkout master
            uses: actions/checkout@master
          - name: Build and publish image
            uses: ilteoood/docker_buildx@master
            with:
              publish: true
              imageName: asdaragon/qiandao # dockerid/imageName
              platform: linux/arm64,linux/amd64,linux/arm/v7 # 你准备构建的镜像平台
              tag: 20210107,latest
              dockerHubUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid 在setting创建secrets name=DOCKER_USERNAME  value=dockerid
              dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }} # docker hub password,在setting创建secrets name=DOCKER_PASSWORD  value=dockerpassword